= Env vars & Configmap

Source: link:https://www.youtube.com/watch?v=-xZ02dEF6kU&list=PL8D2P0ruohOBSA_CDqJLflJ8FLJNe26K-&index=5[youtube] +
PATH: _kuber-learning/src/main/yml/sn06-EnvVars_n_Configmap/..._ +

*Content:*

- 1) Environment variables
- 2) Configmap
  * 2.1) Shell внутри пода (докера)


=== 1) Environment variables

Envs описываются в основном в деплойменте, но могут быть указаны и напрямую на подах/репликасетах:

[source, yaml]
----
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        env:
        - name: TEST
          value: foo
----

Создаем деплоймент:
[source, bash]
----
> kubectl apply -f deployment-with-env.yaml
---------------------------------------
deployment.apps/my-deployment created

> kubectl get pods
---------------------------------------
NAME                             READY   STATUS    RESTARTS   AGE
my-deployment-546499fdb4-f5jxz   1/1     Running   0          7s
----
Посмотрим на то, что у нас есть в контейнере, через describe:
[source, bash]
----
> kubectl describe pod my-deployment-546499fdb4-f5jxz
---------------------------------------
Name:         my-deployment-546499fdb4-f5jxz
Containers:
  nginx:
    Image:          quay.io/testing-farm/nginx:1.12
    Environment:
      TEST:  foo
----
И в разделе `Environment` у контейнера пода увидим нашу env var.

=== 2) Configmap

Проблема: общий для всех контейнеров параметр - например, урл к базе данных. Configmap позволяет не дублировать такие параметры во всех контейнерах, а хранить их в себе. +
Configmap - это ямл-файл, где в разделе `data` в формате ключ-значения описываются env-переменные:
[source, yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-env
data:
  dbhost: postgresql
  DEBUG: "false"
----

Применяем configmap к кластеру:
[source, bash]
----
> kubectl apply -f configmap.yaml
---------------------------------------
configmap/my-configmap-env created

kubectl get cm
---------------------------------------
NAME               DATA   AGE
kube-root-ca.crt   1      4d11h
my-configmap-env   2      78s
----

Первая конфигмапа - `kube-root-ca.crt` - это сертификат кластера (в нем содержится токен).
Вторая - `my-configmap-env` - это уже наша.

Для юзания этой конфигмапы мы должны указать ссылку на нее в контейнере через `envFrom`. +
*_See:_* _deployment-with-env-cm.yaml_:
[source, yaml]
----
spec:
  template:
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        env:
        - name: TEST
          value: foo
        envFrom:
        - configMapRef:
            name: my-configmap-env
----

Применим деплоймент с конфигмапой к существующему поду:
[source, bash]
----
kubectl apply -f deployment-with-env-cm.yaml
---------------------------------------
deployment.apps/my-deployment configured

kubectl get pod
---------------------------------------
NAME                             READY   STATUS    RESTARTS   AGE
my-deployment-7d5646cb7b-hq548   1/1     Running   0          18s
----
Написано "configured", т к такой деплоймент уже существует, его мы и конфигурим. Посмотрим, что у нас теперь лежит в контейнере:
[source, bash]
----
kubectl describe pod my-deployment-7d5646cb7b-hq548
---------------------------------------
Containers:
  nginx:
    Image:          quay.io/testing-farm/nginx:1.12
    Environment Variables from:
      my-configmap-env  ConfigMap  Optional: false
    Environment:
      TEST:  foo
----
В самом поде мы не видим переменные окружения конфигмапы. Можно посмотреть на нее двумя способами:

- 1. Либо посмотреть саму конфигмапу:
[source, bash]
----
> kubectl get cm my-configmap-env -o yaml
---------------------------------------
apiVersion: v1
data:
  DEBUG: "false"
  dbhost: postgresql
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DEBUG":"false","dbhost":"postgresql"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"my-configmap-env","names
pace":"default"}}
  creationTimestamp: "2022-04-20T06:08:29Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:DEBUG: {}
        f:dbhost: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-04-20T06:08:29Z"
  name: my-configmap-env
  namespace: default
  resourceVersion: "231007"
  uid: d6c0ed72-7c88-4173-b456-fa8dc5baab0a

----

==== 2.1) Shell внутри пода (докера)
- 2. Либо зайти во внутрь нашего пода, запустить внутри shell и посмотреть на переменные там командой `env`: +
Как и с докером:
[source, bash]
----
> kubectl exec -it my-deployment-7d5646cb7b-hq548 -- bash
---------------------------------------
root@my-deployment-7d5646cb7b-hq548:/#

root@my-deployment-7d5646cb7b-hq548:/# env
---------------------------------------
HOSTNAME=my-deployment-7d5646cb7b-hq548
NJS_VERSION=1.12.2.0.1.14-1~stretch
TEST=foo
DEBUG=false
NGINX_VERSION=1.12.2-1~stretch
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
PWD=/
HOME=/root
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
TERM=xterm
dbhost=postgresql
SHLVL=1
KUBERNETES_SERVICE_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_SERVICE_HOST=10.96.0.1
_=/usr/bin/env
root@my-deployment-7d5646cb7b-hq548:/#

root@my-deployment-7d5646cb7b-hq548:/# exit
---------------------------------------
exit
command terminated with exit code 130
----
И тут мы уже видим все env переменные, в том числе и те, которые описаны в самом деплойменте:
[source, bash]
----
TEST=foo
DEBUG=false
dbhost=postgresql
----