= Secrets

Source: link:https://www.youtube.com/watch?v=-xZ02dEF6kU&list=PL8D2P0ruohOBSA_CDqJLflJ8FLJNe26K-&index=5[youtube] +
PATH: _kuber-learning/src/main/yml/sn07-Secrets/..._ +

*Content:*

- 1) Secrets intro
  * 1.1) Secrets "--from-literal" command
  * 1.2) EnvVar "valueFrom" - точечное взятие значений из секрета.конфигмапы
- 2) Раздел "stringData" манифеста секрета. Аннотация "last-applied-configuration". Проблемы мержа yaml-ов в кубере
  * 2.1) Тестируем изменение "stringData" еще два раза

=== 1) Secrets intro

В конфигмапах не принято хранить sensitive data. Для этого предназначена отдельная сущность - secret. Структура манифеста у секрета аналогична конфигмапе - там тоже есть раздел `data`, содержащий ключи и значения. +
Секреты бывают нескольких типов:

- *generic* - самый распространенный, для хранения логинов, паролей, токенов и пр. Создается программистами, админами.
- *docker-registry* - данные авторизации в docker-registry.
- *tls* - TLS сертификаты для Ingress - для https и других протоколов с штфрованием данных. +
Два предопределенных ключа: 1) ключ для хранения приватного ключа; 2) ключ для хранения самого подписанного сертификата. +
Вообще, креды TLS указываются в контейнерах для того, чтобы они могли ходить по защищенному соединению - будем говорить об этом позже.

==== 1.1) Secrets "--from-literal" command
Создадим наш сикрет из yml файла:

- `generic` указывает на тип сикрета, `test` - имя сикрета
- через `--from-literal` мы можем создавать новые переменные и задавать их значения в сикрете:

IMPORTANT: Изначально в туториале `--save-config` в команде создания сикрета не было. Мы про эту команду "забыли", а далее показываются side-effects от этого и говорится, почему нам `--save-config` таки нужна при apply/create secret.

[source, bash]
----
> kubectl create secret generic test --from-literal=test1=asdf --from-literal=dbpassword=1q2w3e --save-config
---------------------------------------
secret/test created

> kubectl get secret
---------------------------------------
NAME                  TYPE                                  DATA   AGE
default-token-xwzct   kubernetes.io/service-account-token   3      7d18h
test                  Opaque                                2      19s

> kubectl get secret test -o yaml
---------------------------------------
apiVersion: v1
data:
  dbpassword: MXEydzNl
  test1: YXNkZg==
kind: Secret
metadata:
  creationTimestamp: "2022-04-23T13:07:49Z"
  name: test
  namespace: default
  resourceVersion: "710906"
  uid: 85040a53-4c21-4784-90bd-8de5d480d260
type: Opaque

----
Однако тип у созданного сикрета называется *Opaque* - так исторически сложилось, хотя в реальности сикрет имеет тип *generic*. +
Secret хранит в себе информацию, закодированную в виде base64, и любой человек может декодировать информацию из них. Т е секрет не шифрует, а декодирует sensitive data.

*Вопрос*: зачем тогда "несекретные секреты" нужны, если любой может раскодировать ваши пароли? Почему не в конфиг мапе?
*Ответ*: есть два момента:

- Во-первых, кодировка base64 используется потому, что токены могут хранить самволы, которые yaml просто не воспринимает. Т е кодируем мы не для шифрования, а для того, чтобы сохранить можно было любую информацию
- Во-вторых, сикреты - это отдельные сущности. В кубере есть `rbac` - такая штука, которая позволяет ограничить права пользователя для доступа к определенным ресурсам. +
Стандартная роль "_Edit_" позволяет редачить и просматривать конфигмапы, но не позволяет реактировать сикреты. Сикреты могут смотреть только пользователи с ролью "_Administrator_".

Посмотрим на пример деплоймента в сикретах: +

- 1. Как и в случае с configMap, можно указать ссылку на сикрет через `secretRef`:
[source, yaml]
----
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        envFrom:
        - secretRef:
            name: test
----

==== 1.2) EnvVar "valueFrom" - точечное взятие значений

- 2. Но мы можем и точечно указать, в какую env-переменную какое значение из какого сикрета нам нужно через `valueFrom.secretKeyRef`:
[source, yaml]
----
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        env:
        - name: TEST
          value: foo
        - name: TEST_1
          valueFrom:
            secretKeyRef:
              name: test
              key: test1
----
С помощью такого способа можно выдергивать конкретные ключи в конфигмапе или секрете и передавать в приложение. И при этом мы можем задать другое имя нашей переменной из секрета - например, _TEST_1_

Создадим деплоймент, в котором будет использоваться переменная из сикрета:
[source, bash]
----
> kubectl apply -f deployment-with-secret.yaml
---------------------------------------
deployment.apps/my-deployment created

> kubectl get pods
---------------------------------------
NAME                            READY   STATUS    RESTARTS   AGE
my-deployment-cdf4b4cfc-7lb76   1/1     Running   0          7s

> kubectl describe pod my-deployment-cdf4b4cfc-7lb76
---------------------------------------
Name:         my-deployment-cdf4b4cfc-7lb76
Containers:
  nginx:
    Image:          quay.io/testing-farm/nginx:1.12
    Environment Variables from:
      my-configmap-env  ConfigMap  Optional: false
    Environment:
      TEST:    foo
      TEST_1:  <set to the key 'test1' in secret 'test'>  Optional: false
----

Видим, что мы не можем посмотреть значения сикретов в переменных. Однако мы можем получить доступ к значениям (если у нас не отобрали права *_exec_* в поде) через консоль пода:
[source, bash]
----
> kubectl exec -it my-deployment-cdf4b4cfc-7lb76 -- bash
---------------------------------------
root@my-deployment-cdf4b4cfc-7lb76:/#

> root@my-deployment-cdf4b4cfc-7lb76:/# env
---------------------------------------
HOSTNAME=my-deployment-cdf4b4cfc-7lb76
TEST=foo
DEBUG=false
TEST_1=asdf
dbhost=postgresql
----
Здесь даже нет base64 - сразу исходное значение `TEST_1=asdf`, что опять же говорит нам о том, что кодировка base64 используется только для того, чтобы запихать любые значения сикретов в ямл.

=== 2) Раздел "stringData" манифеста секрета. Аннотация "last-applied-configuration". Проблемы мержа yaml-ов в кубере

А сейчас посмотрим на такую штуку в _kuber-learning/src/main/yml/sn07-Secrets/secret.yaml_:

Как мы уже говорили, у secret есть раздел `data` (в файле он пустой, мы задали значения при создании с помощью "--from-literal" команды). Но в самом файле мы можем увидеть непустой раздел `stringData`, где находится plaintext `test: updated` (там нет кодировки).

Почему мы никогда не видим раздел `stringData` в наших сикретах в кубере? +
Эта штука сделана для удобства админов - чтобы они не перекодировали вручную токены в base64. Пишите все плейнтекстом в разделе stringData, когда кубер это увидит, он сам задекодирует это в base64 и сохранит в раздел `data`.

По сути, это означает, что вы в своем родном yaml-файле пишете конкретные значения, а кубер уже их сам зажекодирует и пользователи увидят данные значения только в кодировке base64. Это в своем роде аналог команды "--from-literal", только в исходном ямле сикрета (не результирующем).

Давайте применим этот сикрет:
[source, bash]
----
> kubectl apply -f secret.yaml
---------------------------------------
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
secret/test configured
----
У нас появился Warning. Мы при создании секрета забыли указать опцию _--save-config_ - и у нас при создании по итогу не была создана в секрете аннотация `kubectl.kubernetes.io/last-applied-configuration`. +
Интересно то, что наш `kubectl apply` ее по итогу создаст (если ее не было в сикрете).

Что это за анноташка и зачем она нужна?
[source, bash]
----
> kubectl get secret test -o yaml
---------------------------------------
apiVersion: v1
data:
  dbpassword: MXEydzNl
  test: dXBkYXRlZA==
  test1: YXNkZg==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"test","namespace":"default"},"stringData":{"test":"updated"}}

----
Есть проблемы, которые относятся к проблемам мержа ямлов. В случае apply мы пытаемся смержить старый и новый yaml-ы сикрета. Допустим, мы из нового файла убрали пропертю, которая присутствует в старом (в нашем случае - это проперти _test1_ и _dbpassword_, которые мы задали при создании сикрета). Кубер не понимает, мы хотим удалить эти переменные или нет? Этот ямл может мержиться как в самом кубере, так и в kubectl и пр.

Для решения данной проблемы как раз и существует анноташка `metadata`.`annotations`.`kubectl.kubernetes.io/last-applied-configuration`. Посмотрим на ее json:
[source, json]
----
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "annotations": {

    },
    "name": "test",
    "namespace": "default"
  },
  "stringData": {
    "test": "updated"
  }
}
----
В json нарисовано то, что было добавлено с помощью `kubectl apply`. И при последующих апплаях кубер будет понимать, что уже было зааплаено, что планируется зааплаить и на основании этого уже решать, как мержить все это дело, какие поля добавить, какие оставить, какие удалить.

Так, собственно, а в чем прикол? У нас же просто добавилась новая переменная test, две старые (test1, dbpassword) не поменялись?

Давайте поменяем secret.yaml следующим образом: заменим в нем под `stringData` переменную `test` на `test1: updated`:
[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  test1: updated
----
Поменяем секрет еще раз и посмотрим на него:
[source, bash]
----
> kubectl apply -f secret.yaml
---------------------------------------
secret/test configured

> kubectl get secret test -o yaml
---------------------------------------
apiVersion: v1
data:
  dbpassword: MXEydzNl
  test: ""
  test1: dXBkYXRlZA==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"test","namespace":"default"},"stringData":{"test1":"updated"}}

----
Теперь у нас:

- `test: ""`,
- `test1: dXBkYXRlZA==` ("dXBkYXRlZA==" = "updated")
- `dbpassword` вообще не затронут

С последними двумя понятно, но почему занулилась первая переменная? Кубер посмотрел на `last-applied-configuration` в предыдущем сикрете и увидел, что `test` мы уже через `apply` делали, а в новом `apply` его уже нету - поэтому мы его просто очистили.

==== 2.1) Тестируем изменение "stringData" еще два раза

Протестировал еще:
[source, yaml]
----
stringData:
  test1: updated
  dbpassword: updated_db
----
Результат: _dbpassword_ изменился, _test_/_test1_ не изменились. Анноташка выглядит так:
[source, json]
----
{"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"test","namespace":"default"},"stringData":{"dbpassword":"updated_db","test1":"updated"}}
----
Т. е. теперь `"stringData":{"dbpassword":"updated_db","test1":"updated"}`

И еще один раз:
[source, yaml]
----
stringData:
  dbpassword: updated_db
----
Результат: _test1_ занулился, _test_/_dbpassword_ не изменились. Анноташка выглядит так:
[source, json]
----
{"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"test","namespace":"default"},"stringData":{"dbpassword":"updated_db"}}
----
Теперь же `"stringData":{"dbpassword":"updated_db"}` - test1 убрался из анноташки.